### PR TITLE
Add more metamethods to the generic JS object

### PR DESCRIPTION
**Pull request by loopspace**
Since all JS objects that are accessible in the Lua VM have the same metatable, it's useful if that metatable is as complete as possible.  This means adding the `__add` functions and similar.  To do this, the number of available functions must be increased (`RESERVED_FUNCTION_POINTERS`) to 18 to get them all in.  Then the functions must be defined and assigned.

Metamethods such as `__add` can be called with the object either first or second.  For example, if `c` is an instance of a class implementing complex numbers, then both `3 + c` and `c + 3` make sense.  Lua will use the metamethod of `c` for both cases, but will keep the order of arguments the same.  So `c`s metamethod must be able to cope with the arguments being either way around, and the underlying function that is called must be able to be called as a class method as well as an instance method.

This pull request implements all of the above.  It's quite possible that it isn't the most elegant way of doing it, but if not then I hope the value of doing this is seen and a better way found.

### CODE REVIEW

**Comment by daurnimator** [comment]
Looking for a `__add` field on a javascript object isn't what I'd expect.
I'd only want to add support for metamethods if they cleanly map to primitive javascript operations. (`__len` using `ob.length` was a slight exception)
e.g. `__add` would just use the javascript `+` operator.
This isn't that useful at the moment (which is why I haven't done it), but might make sense in future once JS gains proper [`Proxy`s with traps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)

What is your use-case for this? I'd expect in most situation you'd wrap the JS object in a lua table with a metatable that gives you nicer lua semantics.

**Comment by loopspace** [comment]
Admittedly, wrapping the JS object in a lua table hadn't occurred to me.  But I think that if I did that, then I'd end up with difficulties elsewhere.

In short, I have a lua layer on top of a JS layer and have information passing back and forth.  As the donkey work is being done in the JS layer, I thought it would be easier to implement if the information being passed was a JS object rather than a Lua object.

My actual use case is that I want to be able to write lua code that can access elements on the webpage, in particular a canvas element.  So I'm defining a number of functions in lua which are thin wrappers around JS functions, for example to draw a rectangle on the canvas element.  The way I'm doing that at the moment is to define the function in JS, since all the functionality is easy in JS, and then just insert that function into the Lua global table.  Since the function is written in JS, it's easier if what is passed to it are JS objects rather than Lua objects.

One of my objects is a 2D vector, so that I can refer to coordinates on the canvas, and in the Lua code I want to be able to add, scale, and so forth with these vectors.  Hence wanting the __add metamethod in the JS object's metatable.

**Comment by daurnimator** [comment]
> In short, I have a lua layer on top of a JS layer and have information passing back and forth. As the donkey work is being done in the JS layer, I thought it would be easier to implement if the information being passed was a JS object rather than a Lua object.

IMO It would be better to do this in lua side.
If you do want to write it in js and have a metatable, you should make a different userdata type. (you don't have to use the generic one I made).

> The way I'm doing that at the moment is to define the function in JS, since all the functionality is easy in JS, and then just insert that function into the Lua global table. Since the function is written in JS, it's easier if what is passed to it are JS objects rather than Lua objects.

> One of my objects is a 2D vector, so that I can refer to coordinates on the canvas, and in the Lua code I want to be able to add, scale, and so forth with these vectors. Hence wanting the __add metamethod in the JS object's metatable.

If `a + b` doesn't work on your JS objects in JS, why should it work on JS objects in Lua

**Comment by loopspace** [comment]
> IMO It would be better to do this in lua side.
I think this might be an "agree to disagree".  I'm of the opinion that since what I'm doing is hidden from the user anyway, there's no reason not to use the bottom layer for the implementation and surely it will be faster to do it in JS than in lua which is then interpreted into JS.

> If you do want to write it in js and have a metatable, you should make a different userdata type. (you don't have to use the generic one I made).
This is what I really wanted to do, but my skills in figuring out what was going on were insufficient to the task.  I couldn't see how to do that.  Do you have an example?

**Comment by daurnimator** [comment]
> I think this might be an "agree to disagree"

I think so. 

> surely it will be faster to do it in JS than in lua which is then interpreted into JS.

Not exactly; asm.js does not usually run in the standard JS intepreter.

> I couldn't see how to do that. Do you have an example?

You just need to write yourself something like the [`pushjs` function](https://github.com/kripken/lua.vm.js/blob/e86bb5bb6a908948b5b2ee13669455c48fd9f523/src/lua.js#L486) that uses a new metatable you create. You don't need any modifications to lua.vm.js to do this.

> Just because I can't do it in JS (again, my search skills have not led me to a way to enable a+b on JS objects),

I linked it above: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
It's not widely supported yet though.

> doesn't mean I shouldn't in Lua.

I think it does. lua.vm.js should only expose JS primitives in the default JS matatable; anything else is out of scope, and should be done in a wrapper or new userdata type.

**Pull request closed without merging**
